name: "AWS Assume Tokens"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  read-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::337909758621:role/whitebox-lab-2-github-actions-role
          role-session-name: OIDCSession

      - name: Get OIDC token
        id: oidc
        run: |
          TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL)
          echo "OIDC_TOKEN=$TOKEN" >> $GITHUB_ENV
          curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL

      - name: Print OIDC token
        run: |
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN
          echo $ACTIONS_ID_TOKEN_REQUEST_URL
